# arch: s390x
dist: focal
# addons:
#   postgresql: "11"
# language: elixir
# group: dev
# language: erlang

# rvm:
# - 2.6.5
# - 2.5.3
# - 2.7.0

cache: bundler

script:
- uname -a
- ps auxfw
- php -v
# - __dots() { while true ; do echo -en . ; sleep 30 ; done } ; __dots &
# - sleep 60000
# - uname -a
# - ruby -v
# - gem env
# - gem list
# - sudo gem list
